language: java
jdk:
  - oraclejdk7

# whitelist
branches:
  only:
    - master

script: mvn validate

after_success:
  - bash ./deploy.sh   

env:
  global:
  - GH_REF: github.com/BorisNaguet/webtools-tapestry.git
  - secure: "cCYHpcONqJhLKXwSrrOGQgQqsaVqaJ1uYzZWKEUJUSlgNFPh5cv6hgjFOJDe4YPhzfWDOH4Mkuepeqjyw/6GZuhB7RU/o2FwI/Vi0lUqYTNyKjTbONKgw2Ut0ytR/Ja3HUKHQ5ZmVHfFREtpG6gHT4x61ZNnbyTFyFThvOzszd46m+QyoCKXJShXE6dbwnJKfjrx+GJcEE5/mHMXebuIFaaKiVwAI0GSF23TqpOn13DGXHG5GW5fVBOaqJZDJ4C3smWqYcv+ePUtc+rQwM9gnuSABxUB91y0Tu9yRERdEmXLwPVc8rBY5Q+tCoYLqliyrRipLOpunu1Ql2np9RQRqGUeH5sRHDpskfsplZLj+MJUtY9ecf3OwHt7pk6dbX7cMbQ2uCZSRb4GgAdlIeGHmj8iKtlxoziMvYxghppQbjNT+UaXsZAhlNwQNDfUg6Ca/WSvwlhIcNBcQwCnyh+ik8tXk1q0sxVsxmg3hn1p3u6i9XuF7qlYQjP9i0FHI+pOdHlBb1C77WJtTujxpE2/Injkv5fdTjOWEG9ogtf1+jlfluagxkVuJGTsjGBKM/XDMiQzJpRHJD9gz7wUi0vfqTa7CwFtziyLvrYiFajoSkp4rTy5XK9zT+t4pXuphtddepafTp0yOHF5TIO5UUttFtAZ682mNJ0RyV+Sz8VxGRw="
